<a href="https://colab.research.google.com/github/poolGolez/tf-playground/blob/main/playground/playing_with_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Fundamentals

In [74]:
import tensorflow as tf

## [1] Create a vector, scalar, matrix, and tensor with arbitrary valuesusing `tf.constant()`

In [75]:
scalar = tf.constant(9)
vector = tf.constant([1, 3, 5])
matrix = tf.constant([[1, 2, 3],
                      [4, 5,6],
                      [7, 8, 9]])
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]],
                      
                      [[0, 0, 0],
                       [0, 0, 0],
                       [0, 0, 0]],
                      
                      [[-1, -2, -3],
                       [-4, -5, -6],
                       [-7, -8, -9]]])

scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 5], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        [[-1, -2, -3],
         [-4, -5, -6],
         [-7, -8, -9]]], dtype=int32)>)

## [2] Find the shape, rank, and size of the tensors you created in 1.

In [76]:
def print_tensor_info(name, tensor):
  print(name)
  print(f"  shape: {tensor.shape}")
  print(f"  rank: {tensor.ndim}")
  print(f"  size: {tf.size(tensor)}")

print_tensor_info("scalar", scalar)
print_tensor_info("vector", vector)
print_tensor_info("matrix", matrix)
print_tensor_info("tensor", tensor)

scalar
  shape: ()
  rank: 0
  size: 1
vector
  shape: (3,)
  rank: 1
  size: 3
matrix
  shape: (3, 3)
  rank: 2
  size: 9
tensor
  shape: (3, 3, 3)
  rank: 3
  size: 27


## [3] Create two tensors containing random values between 0 and1 with shape `[5, 300]`

In [77]:
random_tensor_1 = tf.random.uniform(shape=[5, 300])
random_tensor_2 = tf.random.uniform(shape=[5, 300])

## [4] Multiply the two tensors you created in 3 using matrix multiplication.

In [78]:
tf.matmul(random_tensor_1, tf.transpose(random_tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.334045, 82.66435 , 80.862305, 80.388054, 77.36191 ],
       [71.60903 , 77.18742 , 75.63551 , 73.49542 , 71.3161  ],
       [76.05688 , 81.83431 , 78.07669 , 77.497086, 71.14624 ],
       [76.13844 , 82.29944 , 76.792336, 78.20884 , 73.3691  ],
       [68.983215, 74.95927 , 71.655426, 73.57275 , 70.551674]],
      dtype=float32)>

In [79]:
random_tensor_1 @ tf.transpose(random_tensor_2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.334045, 82.66435 , 80.862305, 80.388054, 77.36191 ],
       [71.60903 , 77.18742 , 75.63551 , 73.49542 , 71.3161  ],
       [76.05688 , 81.83431 , 78.07669 , 77.497086, 71.14624 ],
       [76.13844 , 82.29944 , 76.792336, 78.20884 , 73.3691  ],
       [68.983215, 74.95927 , 71.655426, 73.57275 , 70.551674]],
      dtype=float32)>

## [5] Multiply the two tensors you created in 3 using dot product.

In [80]:
tf.tensordot(random_tensor_1, tf.transpose(random_tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.334045, 82.66435 , 80.862305, 80.388054, 77.36191 ],
       [71.60903 , 77.18742 , 75.63551 , 73.49542 , 71.3161  ],
       [76.05688 , 81.83431 , 78.07669 , 77.497086, 71.14624 ],
       [76.13844 , 82.29944 , 76.792336, 78.20884 , 73.3691  ],
       [68.983215, 74.95927 , 71.655426, 73.57275 , 70.551674]],
      dtype=float32)>

## [6] Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [81]:
random_tensor_3 = tf.random.uniform(shape=(5, 12, 3))
random_tensor_3

<tf.Tensor: shape=(5, 12, 3), dtype=float32, numpy=
array([[[0.06752515, 0.76291263, 0.07966197],
        [0.36119998, 0.1050241 , 0.66084087],
        [0.8669733 , 0.61866367, 0.63318884],
        [0.3179165 , 0.8926009 , 0.5062319 ],
        [0.49257708, 0.3385166 , 0.9176047 ],
        [0.37595356, 0.6411327 , 0.2158246 ],
        [0.6470537 , 0.39620733, 0.53760636],
        [0.8166537 , 0.5637735 , 0.5423118 ],
        [0.18504858, 0.7138536 , 0.09292114],
        [0.39713597, 0.12964118, 0.56368375],
        [0.4141463 , 0.34799552, 0.21276617],
        [0.01889968, 0.9607445 , 0.604275  ]],

       [[0.05955362, 0.18875647, 0.7755828 ],
        [0.6565707 , 0.6222254 , 0.861519  ],
        [0.6360998 , 0.46307325, 0.4076867 ],
        [0.78237545, 0.61358225, 0.17710996],
        [0.5052564 , 0.92607474, 0.4975909 ],
        [0.86884415, 0.0361408 , 0.42015684],
        [0.95591295, 0.799108  , 0.29930604],
        [0.00185931, 0.8088237 , 0.914863  ],
        [0.3176905 , 0.556

## [7] Find the min and max values of the tensor you created in 6 along the first axis.

In [82]:
# E = tf.constant([[[1,2, 13],
#                  [4,5,6]],
                 
#                  [[7, 8, 9],
#                  [10, -11, 12]]])
# E, tf.reduce_max(E, axis=0)
# tf.reduce_max(random_tensor_3, axis=0)
random_tensor_3, tf.reduce_max(random_tensor_3, axis=0)

(<tf.Tensor: shape=(5, 12, 3), dtype=float32, numpy=
 array([[[0.06752515, 0.76291263, 0.07966197],
         [0.36119998, 0.1050241 , 0.66084087],
         [0.8669733 , 0.61866367, 0.63318884],
         [0.3179165 , 0.8926009 , 0.5062319 ],
         [0.49257708, 0.3385166 , 0.9176047 ],
         [0.37595356, 0.6411327 , 0.2158246 ],
         [0.6470537 , 0.39620733, 0.53760636],
         [0.8166537 , 0.5637735 , 0.5423118 ],
         [0.18504858, 0.7138536 , 0.09292114],
         [0.39713597, 0.12964118, 0.56368375],
         [0.4141463 , 0.34799552, 0.21276617],
         [0.01889968, 0.9607445 , 0.604275  ]],
 
        [[0.05955362, 0.18875647, 0.7755828 ],
         [0.6565707 , 0.6222254 , 0.861519  ],
         [0.6360998 , 0.46307325, 0.4076867 ],
         [0.78237545, 0.61358225, 0.17710996],
         [0.5052564 , 0.92607474, 0.4975909 ],
         [0.86884415, 0.0361408 , 0.42015684],
         [0.95591295, 0.799108  , 0.29930604],
         [0.00185931, 0.8088237 , 0.914863  ],
    

In [83]:
words = [1,2,3,2,1,12]
import numpy as np
np.max(words), tf.one_hot(words, depth=np.max(words) + 1)

(12, <tf.Tensor: shape=(6, 13), dtype=float32, numpy=
 array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
       dtype=float32)>)

## [8] Create a tensor with random values of shape `[1, 224, 224, 3]`, then squeeze it to change the shape to `[224, 224, 3]`

In [87]:
expanded_tensor = tf.random.normal(shape=[1, 224, 224, 3])
squeezed_tensor = tf.squeeze(expanded_tensor)

expanded_tensor.shape,squeezed_tensor.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

## [9] Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [94]:
tensor_10_values = tf.constant([-82., -73, 11., -8., 16., 45., 22., 13., 11., 39.])

tensor_10_values, tf.argmax(tensor_10_values)

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([-82., -73.,  11.,  -8.,  16.,  45.,  22.,  13.,  11.,  39.],
       dtype=float32)>, <tf.Tensor: shape=(), dtype=int64, numpy=5>)

## [10] One-hot encode the tensor you created in 9

In [97]:
tf.one_hot(tf.cast(tensor_10_values, dtype=tf.int64), depth = 100)

<tf.Tensor: shape=(10, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.,